POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "jagan",
  "name": "jagan",
  "password": "jagan_123",
  "gender": "male",
  "location": "Detroit"
}
###
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "maya",
  "password": "maya_123"
}

###
PUT http://localhost:3000/change-password
Content-Type: application/json

{
  "username": "jagan",
  "oldPassword": "jagan_123",
  "newPassword": "jagan_111"
}

